<a href="https://colab.research.google.com/github/shivamneeraj23/deep_learning_with_pytorch/blob/master/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Imports the torch module
import torch

In [5]:
# Creates a one-dimensional tensor of size 3 filled with 1s
a = torch.ones(3)

In [6]:
a

tensor([1., 1., 1.])

In [8]:
float(a[1])

1.0

In [20]:
"""
We are storing all the points as a list of all the cordinates of the triangle, 
x cordinate in odd places and y in even places
"""

points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])

In [21]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [22]:
points.shape

torch.Size([6])

In [17]:
"""
We are storing the points as (x,y) pair
"""
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [18]:
points[0]

tensor([4., 1.])

In [19]:
points.shape

torch.Size([3, 2])

In [7]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]

In [24]:
img_t

tensor([[[ 0.7394, -1.4989,  1.4434, -0.4643, -0.1264],
         [ 0.0869,  1.6064,  0.7058,  1.4784, -1.5146],
         [-1.4187, -0.4091, -0.7729, -1.2944,  0.5705],
         [-1.1994, -0.0953, -1.1998,  0.1060,  0.7736],
         [ 0.9098,  1.3020,  0.0528,  0.0709,  0.9171]],

        [[ 0.9158, -1.8349, -0.0219, -0.1350, -0.4613],
         [ 0.2999, -0.1424,  0.0171,  1.5912,  1.0075],
         [ 1.1135, -1.2250, -1.5755,  1.4300,  0.2868],
         [ 1.3583, -0.7200,  0.8518, -1.1487, -1.3931],
         [ 0.9435, -0.0672, -0.5707, -1.3334, -0.5937]],

        [[-0.5692,  0.3995,  1.8115, -0.3702, -0.4847],
         [ 1.0624,  0.9455,  0.5469,  0.0425,  1.0902],
         [-0.0468, -1.1532,  0.1132, -0.9637,  0.7045],
         [-0.5091, -0.0231,  0.7919,  0.0877, -0.0634],
         [ 0.1227, -0.9199, -0.4937, -0.7561,  0.2228]]])

In [3]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [8]:
img_gray_naive = img_t.mean(-3)

In [9]:
img_gray_naive

tensor([[ 0.2161,  0.2059, -0.1378,  0.4106,  0.4336],
        [-0.1967, -0.4636, -0.4221, -0.1994,  0.1623],
        [ 0.1883,  0.1393, -1.0258, -0.7932, -0.7473],
        [ 0.2471,  0.0579,  0.3958,  0.6643,  0.5166],
        [ 0.0522,  0.2243,  0.2064,  0.4262,  0.7123]])

In [10]:
batch_gray_naive = batch_t.mean(-3)

In [11]:
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

Defining Named Tensors in Pytorch as unamed tensors leads to a lot of confusion

In [13]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:840.)
  """Entry point for launching an IPython kernel.


In [19]:
weights_named.shape

torch.Size([3])

Refining Name of Unamed tensors 

In [15]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')

In [16]:
img_named

tensor([[[ 0.0355, -0.1360,  0.4669,  0.3779, -1.6713],
         [ 0.5710, -1.0845,  0.3073, -1.5804,  0.6618],
         [ 1.2415,  1.1004, -1.7466, -0.6275, -0.6986],
         [-0.7561,  0.0362, -0.8625,  0.2569,  0.5807],
         [-1.1030,  0.9727,  0.8205, -0.7019,  0.8770]],

        [[ 0.8543,  0.0242,  0.3515,  0.1931,  0.9706],
         [-0.7333, -0.0134, -0.2288,  0.2369,  1.7131],
         [-1.0182, -0.3387, -1.5403, -0.7116, -2.8139],
         [-0.1727,  1.0527,  0.6488, -0.7788,  2.1436],
         [-0.2342, -0.1741,  1.0119,  1.7116,  0.1216]],

        [[-0.2415,  0.7294, -1.2318,  0.6609,  2.0014],
         [-0.4277, -0.2930, -1.3448,  0.7454, -1.8880],
         [ 0.3415, -0.3437,  0.2094, -1.0405,  1.2705],
         [ 1.6703, -0.9152,  1.4012,  2.5148, -1.1744],
         [ 1.4938, -0.1257, -1.2133,  0.2689,  1.1381]]],
       names=('channels', 'rows', 'columns'))

For operations with two inputs, in addition to the usual dimension checks—whether
sizes are the same, or if one is 1 and can be broadcast to the other—PyTorch will now
check the names for us. So far, it does not automatically align dimensions, so we need
to do this explicitly. The method align_as returns a tensor with missing dimensions
added and existing ones permuted to the right order:

In [17]:

weights_aligned = weights_named.align_as(img_named)

In [18]:
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [20]:
gray_named = (img_named * weights_aligned).sum('channels')

In [21]:
gray_named

tensor([[ 0.6011,  0.0411,  0.2617,  0.2661,  0.4833],
        [-0.4340, -0.2613, -0.1954, -0.1127,  1.2296],
        [-0.4396, -0.0331, -1.4579, -0.7175, -2.0693],
        [-0.1637,  0.6945,  0.3818, -0.3208,  1.5718],
        [-0.2941,  0.0732,  0.8106,  1.0944,  0.3556]],
       names=('rows', 'columns'))